stages:
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUST_BACKTRACE: 1

cache:
  paths:
    - .cargo/
    - target/

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo test
    - cargo build --verbose --release
    - mv target/release/octaaf-client ./
  artifacts:
    name: octaaf-client
    paths:
      - octaaf-client
