[package]
name = "kaliquote"
version = "0.1.0"
authors = ["bart"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
serde = "1.0"
serde_derive = "1.0"
libc = "0.2.50"

[profile.release]
lto = true
panic = 'abort'
